# Generated by Django 5.2 on 2025-04-26 14:20

import api.upload_image_file
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('image', models.ImageField(upload_to=api.upload_image_file.dog_image_upload_path)),
            ],
        ),
    ]
